# Generated by Django 5.0.1 on 2026-02-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable/disable access to the proxied server'),
        ),
        migrations.AddField(
            model_name='event',
            name='server_port',
            field=models.IntegerField(blank=True, help_text='Port number for proxied server (e.g., 8080). Leave empty if no server.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated URL slug from title', max_length=200, unique=True),
        ),
    ]
