# Generated by Django 5.0.1 on 2026-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rewrite_urls',
            field=models.BooleanField(default=True, help_text='Rewrite URLs in proxied responses. Disable if the backend is configured with the correct base URL.'),
        ),
    ]
