# Generated by Django 5.0 on 2026-01-29 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name_plural': 'Algorithm Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief explanation of the algorithm')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('c', 'C')], default='python', help_text='Programming language', max_length=20)),
                ('code', models.TextField(help_text='Code for the algorithm')),
                ('time_complexity', models.CharField(blank=True, help_text='e.g., O(n log n)', max_length=100)),
                ('space_complexity', models.CharField(blank=True, help_text='e.g., O(n)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order within category (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='cheatsheet.algorithmcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
