# Generated by Django 5.0 on 2026-01-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'ordering': ['category__name', 'title']},
        ),
        migrations.AlterModelOptions(
            name='algorithmcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Algorithm Categories'},
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='order',
        ),
        migrations.RemoveField(
            model_name='algorithmcategory',
            name='order',
        ),
    ]
