# Generated by Django 5.0 on 2026-01-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheet', '0002_alter_algorithm_options_and_more'),
    ]

    operations = [
    ]
