# Generated by Django 5.0 on 2026-01-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('theme', models.CharField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('link', models.CharField(primary_key=True, serialize=False)),
                ('platform', models.CharField()),
                ('solution_link', models.CharField()),
                ('done', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems', to='board.meet')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('autumn', 'Automne'), ('winter', 'Hiver'), ('summer', 'Été')])),
                ('year', models.IntegerField()),
                ('local', models.CharField(default='AA-3189')),
                ('time', models.TimeField()),
            ],
            options={
                'unique_together': {('season', 'year')},
            },
        ),
        migrations.AddField(
            model_name='meet',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meets', to='board.session'),
        ),
    ]
