# Generated by Django 5.0 on 2026-01-29 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('theme', models.CharField(blank=True, default='', max_length=200)),
                ('contest_link', models.CharField(blank=True, default='', max_length=500)),
                ('managers', models.ManyToManyField(blank=True, related_name='meets_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('link', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=100)),
                ('solution_link', models.CharField(blank=True, default='', max_length=500)),
                ('meets', models.ManyToManyField(blank=True, related_name='problems', to='board.meet')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('autumn', 'Automne'), ('winter', 'Hiver'), ('summer', 'Été')], max_length=10)),
                ('year', models.IntegerField()),
                ('local', models.CharField(default='AA-3189', max_length=100)),
                ('time', models.TimeField()),
                ('day', models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], default='wednesday', max_length=10)),
            ],
            options={
                'ordering': ['-year', 'season'],
                'unique_together': {('season', 'year')},
            },
        ),
        migrations.AddField(
            model_name='meet',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meets', to='board.session'),
        ),
    ]
