# Generated by Django 5.0 on 2026-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty_number',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
