# Generated by Django 5.0 on 2026-01-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution_link',
            field=models.CharField(blank=True, default=''),
        ),
    ]
