# Generated by Django 5.0 on 2026-01-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_problem_solution_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
