# Generated by Django 5.0 on 2026-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_problem_difficulty_problem_difficulty_number'),
        ('cheatsheet', '0003_algorithm_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Algorithm categories/themes for this problem', related_name='problems', to='cheatsheet.algorithmcategory'),
        ),
    ]
