# Generated by Django 5.0 on 2026-01-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_problem_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='theme',
        ),
    ]
