# Generated by Django 5.0 on 2026-01-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_meet_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-year', 'season']},
        ),
    ]
