# Generated by Django 5.0 on 2026-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_meet_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
