# Generated by Django 5.0 on 2026-01-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_session_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='day',
            field=models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi'), ('sunday', 'Dimanche')], default='wednesday'),
        ),
    ]
