# Generated by Django 5.0 on 2026-01-24 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_meet_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='manager',
        ),
        migrations.AddField(
            model_name='meet',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='meets_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
