# Generated by Django 5.0 on 2026-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_meet_manager_meet_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
