# Generated by Django 5.0 on 2026-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_meet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='contest_link',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meet',
            name='get_problems',
            field=models.BooleanField(default=True),
        ),
    ]
