# Generated by Django 5.0 on 2026-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_meet_contest_link_meet_get_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='get_problems',
            field=models.BooleanField(default=False),
        ),
    ]
