# Generated by Django 5.0 on 2026-01-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_meet_get_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
