# Generated by Django 5.0 on 2026-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_meet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='done',
        ),
        migrations.AddField(
            model_name='problem',
            name='meets',
            field=models.ManyToManyField(blank=True, related_name='problems', to='board.meet'),
        ),
    ]
