# Generated by Django 5.0 on 2026-01-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_remove_problem_done_problem_meets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='get_problems',
        ),
    ]
